language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.5
env:
  global:
    - DB=mysql
    - RAILS_ENV=test
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - cp .env-example .env
  - cp config/database.travis.yml config/database.yml
  - mkdir tmp
  - mkdir tmp/cache
  - IMPORT_PAGES=1 FROM=mobile bundle exec rake --trace db:create db:migrate db:test:prepare db:seed
script:
  - bundle exec rake spec
